#!/usr/bin/env python3

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))

from src.rqt_humicpkg.humic_module import HumicMonitor
from rqt_gui.main import Main

plugin = 'rqt_humicpkg'
main = Main(filename=plugin)    
sys.exit(main.main(standalone=plugin))